SMS/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('adminapp.urls')),
    path('facultyapp/', include('facultyapp.urls')),
    path('studentapp/', include('studentapp.urls')),
]

facultyapp/urls.py
from django.urls import path,include
from . import views
app_name = 'facultyapp'
urlpatterns=[
    path('facultyhomepage/', views.facultyhomepage, name='facultyhomepage'),
    path('add_blog/',views.add_blog,name='add_blog'),
    path('<int:pk>/delete/',views.delete_blog,name='delete_blog'),
    path('view_student_list/',views.view_student_list,name='view_student_list'),
    path('add_course/',views.add_course,name='add_course'),
    path('post_marks/',views.post_marks,name='post_marks'),
]

studentapp/urls.py
from django.urls import path, include
from . import views
app_name = 'studentapp'
urlpatterns = [
    #path('projectstudentpage/', views.projectstudentpage, name='projectstudentpage'),
    path('studenthomepage', views.studenthomepage, name='studenthomepage'),
    path('view_marks',views.view_marks,name='view_marks'),
]

templates/NavBar/FacultyNavBar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-danger">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'projecthomepage' %}">SMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'add_student' %}">Add Student</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'student_list' %}">Student List</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyapp:add_blog' %}">Blogs</a>
        </li>
             <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyapp:add_course' %}">ADD COURSE</a>

        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyapp:view_student_list' %}">COURSES ASSIGNED</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyapp:post_marks' %}">POST MARKS</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
    <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'RegisterLogic' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'UserLoginLogic' %}">Login</a>

        </li>
        {% endif %}

 </li>

      </ul>
  </div>
</nav>
{% block body %}

{% endblock %}
</body>
</html>

templates/NavBar/ProjectNavBar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-danger">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'projecthomepage' %}"><b>SMS</b></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"><b>Home</b></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"><b>Link</b></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <b>  PFSD Concepts </b>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'printpagecall' %}">Printer</a></li>
            <li><a class="dropdown-item" href="{% url 'exceptionpagecall' %}">Exception Handling</a></li>
               <li><a class="dropdown-item" href="{% url 'randompagecall' %}">Random Generator</a></li>
              <li><a class="dropdown-item" href="{% url 'calculatorpagecall' %}">Simple Calculator</a></li>
                 <li><a class="dropdown-item" href="{% url 'datetimepagecall' %}">Date and Time Calculator</a></li>
              <li><a class="dropdown-item" href="{% url 'add_task' %}">To Do List</a></li>
              <li><a class="dropdown-item" href="{% url 'upload_file' %}">Upload File</a></li>
               <li><a class="dropdown-item" href="{% url 'user_feedback' %}">Feedback Form</a></li>
              <li><a class="dropdown-item" href="{% url 'manage_contacts' %}">Contact Info</a></li>

            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><b>Search</b></button>
      </form>
    </div>
    <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}"><b>Logout</b></a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'UserRegisterLogic' %}"><b>Register</b></a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'UserLoginLogic' %}"><b>Login</b></a>
        </li>
        {% endif %}

 </li>

      </ul>
  </div>
</nav>
{% block body %}

{% endblock %}
</body>
</html>

templates/NavBar/StudentNavBar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-danger">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'projecthomepage' %}">SMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>

        </li>
          <li class="nav-item">
          <a class="nav-link" href="#">COURSES ASSIGNED</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'studentapp:view_marks' %}">VIEW MARKS</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
    <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'RegisterLogic' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'UserLoginLogic' %}">Login</a>

        </li>
        {% endif %}

 </li>

      </ul>
  </div>
</nav>
{% block body %}

{% endblock %}
</body>
</html>